language: java

sudo: false

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

# Start a display for the gui tests
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
  - mvn -DrepoToken=$COVERALLS_TOKEN jacoco:report coveralls:report